export const LOAD_CATEGORIES = 'LOAD_CATEGORIES';
export const CATEGORIES_LOADING = 'CATEGORIES_LOADING';

export const LOAD_ROOMS = 'LOAD_ROOMS';
export const ROOMS_LOADING = 'ROOMS_LOADING';

export const LOAD_BOOKED = 'LOAD_BOOKED';
export const BOOKED_LOADING = 'BOOKED_LOADING';

export const ADD_COMMENT = 'ADD_COMMENT';
export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const COMMENTS_LOADING = 'COMMENTS_LOADING';


export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const AUTH_FAILED = 'AUTH_FAILED';
export const AUTH_LOADING = 'AUTH_LOADING';
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
